!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2.datasets.dense_design_matrix.DenseDesignMatrix {
        X: !pkl: %(mnist_train_X_path)s
    },
    model: !obj:train_AE.MLP_autoencoder_Dropout {
        batch_size: %(batch_size)i,
        layers: [
                    %(layers_spec)s
                ],
        nvis: 784,
        monitor_targets: False,
        input_include_probs: {
            %(input_probs)s
        },
        input_scales: {
            %(input_scales)s
        }
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate: %(lr)f,
        monitoring_dataset:
            {
                'train' : *train
            },
        cost: %(cost)s {},
        termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: %(max_epochs)i
                }
    },
    save_path: %(save_path)s,
    save_freq: 2
}